Module1 task1
htmlacademy-vue/224714-pizza-1 pull request #1
Opened 2021-07-11 16:31 UTC by allweek

К сожалению шрифты не подключились, не знаю в чем ошибка

2021-07-13 18:29 UTC, Gimir requested changes
Только два маленьких момента. Первый не дает запустить проект, по этому придется его исправить.

2021-07-13 18:29 UTC, Gimir commented on src/frontend/src/App.vue
> +import AppLayout from "@/views/Index";
Или убрать второй index.js или уточнить, что импортируется Index.vue. Иначе проект не собирается.

2021-07-13 18:29 UTC, Gimir commented on src/frontend/src/views/Index.vue
> +<style lang="scss" scoped>
Шрифты не подключаются по тому что у тега <style> проставлен аттрибут scoped

2021-07-16 14:39 UTC, allweek commented on src/frontend/src/App.vue
> +import AppLayout from "@/views/Index";
index.js у этого CLI создался почти в каждой папке пустой, удалил все пустые

2021-07-16 14:54 UTC, allweek commented on src/frontend/src/views/Index.vue
> +<style lang="scss" scoped>
Спасибо! Поправил - заработало! 
А ошибки такого плана можно как-то убрать:

/home/alex/Alex/224714-pizza-1/src/frontend/src/views/Index.vue
Error:(249, 10) Cannot resolve directory '@'

Хотя alias прописан в vue.config и всё работает
alias: {
        "@": path.resolve(__dirname, "src"),
      },

2021-07-17 18:45 UTC, merged